[package]
name = "processor-rs"
version = "0.1.0"
authors = ["Kostas Kolivas <kwstaskolivas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
