---
workers: # Specifies the number of threads each type of worker will use. If the value of `workers` is `auto`,
         # then all of the system's available threads (logical) will be used, distributed to the different worker types.
         # Alternatively, each type's thread number can be specified. If `workers`' value is not `auto` and a worker type
         # is not specified, then it will default to `1`
  processors: num_processors # The number of threads the processor will use
  feeders: num_feeders # The number of feeder threads that will provide data to the processors
  loaders: num_loaders # The number of DB loader threads that will consume processed data and store them in the DB
yara_rule_dir: path_to_dir # The root of the directory which contains all `.yar` files
database:
    user: username # Default: postgres
    passwd: password # Either set this, or the INFOBSERVE_POSTGRES_PASSWD environmental variable
                     # (this value takes precedence). Default: infobserve
    db_name: database # The database to connect. Default: infobserve
    host: host # Default: localhost
    port: port # Default: 5432
redis:
    host: host # Default: localhost
    port: port # Default: 6379
